# Generated by Django 5.0.1 on 2024-05-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.SmallIntegerField(default=0, help_text='AZN'),
        ),
    ]
